const PDFDocument = require('pdfkit');

const drawHeader = (doc, { generatedBy, department, total }) => {
  doc.fontSize(18).fillColor('#172554').text('COMPANY AI', { align: 'center' });
  doc.fontSize(12).fillColor('#334155').text('EMPLOYEE DIRECTORY', { align: 'center' });
  doc.moveDown(0.8);
  doc.fontSize(9).fillColor('#475569')
    .text(`Generated By: ${generatedBy}`)
    .text(`Generated Date: ${new Date().toLocaleString()}`)
    .text(`Department: ${department || 'All Departments'}`)
    .text(`Total Employees: ${total}`);
  doc.moveDown(0.8);
};

const createEmployeePdf = ({ employees, generatedBy, department }) => {
  const doc = new PDFDocument({ size: 'A4', margin: 36, bufferPages: true });
  const columns = [
    ['ID', 48], ['Name', 92], ['Email', 125], ['Department', 78], ['Designation', 82], ['Type', 52], ['Status', 48], ['Joined', 62],
  ];
  const rowHeight = 25;
  let y = 150;

  drawHeader(doc, { generatedBy, department, total: employees.length });

  const drawTableHeader = () => {
    doc.rect(36, y, 487, rowHeight).fill('#172554');
    let x = 40;
    doc.fillColor('#ffffff').fontSize(7);
    columns.forEach(([label, width]) => { doc.text(label, x, y + 8, { width: width - 4 }); x += width; });
    y += rowHeight;
  };

  drawTableHeader();
  employees.forEach((employee, index) => {
    if (y > 755) { doc.addPage(); y = 42; drawTableHeader(); }
    if (index % 2 === 0) doc.rect(36, y, 487, rowHeight).fill('#f1f5f9');
    let x = 40;
    const values = [
      employee.employeeId || employee.id,
      employee.name,
      employee.email,
      employee.department,
      employee.designation || employee.role,
      employee.employeeType || employee.category,
      employee.status || 'ACTIVE',
      employee.joiningDate || '',
    ];
    doc.fillColor('#0f172a').fontSize(6.5);
    values.forEach((value, valueIndex) => {
      const width = columns[valueIndex][1];
      doc.text(String(value || '-'), x, y + 8, { width: width - 4, ellipsis: true });
      x += width;
    });
    y += rowHeight;
  });

  const pages = doc.bufferedPageRange();
  for (let page = 0; page < pages.count; page += 1) {
    doc.switchToPage(page);
    doc.fontSize(8).fillColor('#64748b').text(`Company AI | Page ${page + 1} of ${pages.count}`, 36, 805, { align: 'center', width: 487 });
  }
  doc.end();
  return doc;
};

module.exports = { createEmployeePdf };
