const PERMISSIONS = Object.freeze({
  VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  VIEW_ALLOWED_EMPLOYEE_INFORMATION: 'VIEW_ALLOWED_EMPLOYEE_INFORMATION',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  EDIT_EMPLOYEE: 'EDIT_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  DOWNLOAD_EMPLOYEES: 'DOWNLOAD_EMPLOYEES',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  USE_AI: 'USE_AI',
  ADMIN_EMPLOYEE_VIEW: 'ADMIN_EMPLOYEE_VIEW',
  ADMIN_EMPLOYEE_CREATE: 'ADMIN_EMPLOYEE_CREATE',
  ADMIN_EMPLOYEE_EDIT: 'ADMIN_EMPLOYEE_EDIT',
  ADMIN_EMPLOYEE_DELETE: 'ADMIN_EMPLOYEE_DELETE',
  ADMIN_EMPLOYEE_EXPORT_PDF: 'ADMIN_EMPLOYEE_EXPORT_PDF',
});

const ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.DOWNLOAD_EMPLOYEES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.USE_AI,
    PERMISSIONS.ADMIN_EMPLOYEE_VIEW,
    PERMISSIONS.ADMIN_EMPLOYEE_CREATE,
    PERMISSIONS.ADMIN_EMPLOYEE_EDIT,
    PERMISSIONS.ADMIN_EMPLOYEE_DELETE,
    PERMISSIONS.ADMIN_EMPLOYEE_EXPORT_PDF,
  ],
  HR: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.DOWNLOAD_EMPLOYEES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.USE_AI,
  ],
  MANAGER: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.USE_AI,
  ],
  EMPLOYEE: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.VIEW_ALLOWED_EMPLOYEE_INFORMATION,
    PERMISSIONS.USE_AI,
  ],
});

const isValidRole = (role) => Object.prototype.hasOwnProperty.call(ROLE_PERMISSIONS, role);

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, isValidRole };
