const PERMISSIONS = Object.freeze({
  VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  VIEW_ALLOWED_EMPLOYEE_INFORMATION: 'VIEW_ALLOWED_EMPLOYEE_INFORMATION',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  EDIT_EMPLOYEE: 'EDIT_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  DOWNLOAD_EMPLOYEES: 'DOWNLOAD_EMPLOYEES',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  USE_AI: 'USE_AI',
  ADMIN_EMPLOYEE_VIEW: 'ADMIN_EMPLOYEE_VIEW',
  ADMIN_EMPLOYEE_CREATE: 'ADMIN_EMPLOYEE_CREATE',
  ADMIN_EMPLOYEE_EDIT: 'ADMIN_EMPLOYEE_EDIT',
  ADMIN_EMPLOYEE_DELETE: 'ADMIN_EMPLOYEE_DELETE',
  ADMIN_EMPLOYEE_EXPORT_PDF: 'ADMIN_EMPLOYEE_EXPORT_PDF',
  VIEW_ATTENDANCE: 'VIEW_ATTENDANCE',
  VIEW_OWN_ATTENDANCE: 'VIEW_OWN_ATTENDANCE',
  MANAGE_ATTENDANCE: 'MANAGE_ATTENDANCE',
  REVIEW_ATTENDANCE_CORRECTIONS: 'REVIEW_ATTENDANCE_CORRECTIONS',
  MANAGE_ATTENDANCE_POLICY: 'MANAGE_ATTENDANCE_POLICY',
});

const ROLE_PERMISSIONS = Object.freeze({
  ADMIN: [...Object.values(PERMISSIONS)],
  HR: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.USE_AI,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.REVIEW_ATTENDANCE_CORRECTIONS,
  ],
  EMPLOYEE: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.VIEW_ALLOWED_EMPLOYEE_INFORMATION,
    PERMISSIONS.USE_AI,
    PERMISSIONS.VIEW_OWN_ATTENDANCE,
  ],
});

const isValidRole = (role) => Object.prototype.hasOwnProperty.call(ROLE_PERMISSIONS, role);

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, isValidRole };
